window.OCTRA_CATEGORIES = [
  "official",
  "wallets",
  "explorers",
  "defi",
  "bridges",
  "launchpads",
  "privacy tools",
  "ai agents",
  "social",
  "developer",
  "infrastructure",
  "resources",
  "watchlist",
];

window.OCTRA_STATUSES = ["active", "in development", "testnet", "beta", "announced", "watchlist"];

window.OCTRA_PROJECTS = [
  {
    name: "octra",
    category: "official",
    status: "active",
    confidence: "verified",
    description: "privacy blockchain network and core ecosystem entrypoint.",
    website: "https://octra.org",
    twitter: "https://x.com/octra",
    github: "https://github.com/octra-labs",
    docs: "https://docs.octra.org",
    source: "https://docs.octra.org",
    featured: true,
  },
  {
    name: "octra docs",
    category: "resources",
    status: "active",
    confidence: "verified",
    description: "official user, developer, validator, and technical documentation.",
    website: "https://docs.octra.org",
    twitter: "https://x.com/octra",
    source: "https://docs.octra.org",
    featured: true,
  },
  {
    name: "octralex",
    category: "official",
    status: "active",
    confidence: "verified",
    description: "octra co-founder / developer account.",
    website: "https://x.com/octralex",
    twitter: "https://x.com/octralex",
    source: "https://x.com/octralex",
  },
  {
    name: "lambda0xE",
    category: "official",
    status: "active",
    confidence: "verified",
    description: "octra co-founder / developer account.",
    website: "https://x.com/lambda0xE",
    twitter: "https://x.com/lambda0xE",
    source: "https://x.com/lambda0xE",
  },
  {
    name: "octrascan",
    category: "explorers",
    status: "active",
    confidence: "verified",
    description: "lite explorer for octra network activity, recent transactions, epochs, supply, and staging metrics.",
    website: "https://octrascan.io",
    twitter: "https://x.com/octra",
    source: "https://octrascan.io",
    featured: true,
  },
  {
    name: "octra faucet",
    category: "official",
    status: "active",
    confidence: "verified",
    description: "official testnet faucet for getting octra network tokens.",
    website: "https://faucet.octra.network/",
    twitter: "https://x.com/octra",
    source: "https://docs.octra.org",
  },
  {
    name: "devnet faucet",
    category: "official",
    status: "testnet",
    confidence: "verified",
    description: "devnet faucet used by builders and testers.",
    website: "https://faucet-devnet.octra.com/",
    twitter: "https://x.com/octra",
    source: "https://docs.octra.org",
  },
  {
    name: "woct",
    category: "bridges",
    status: "active",
    confidence: "verified",
    description: "wrapped oct asset on ethereum used for liquidity and bridge flows.",
    website: "https://etherscan.io/token/0x4647e1fe715c9e23959022c2416c71867f5a6e80",
    twitter: "https://x.com/octra",
    docs: "https://docs.octra.org",
    source: "https://docs.octra.org",
  },
  {
    name: "octra bridge",
    category: "bridges",
    status: "active",
    confidence: "verified",
    description: "official bridge flow between native oct and wrapped oct.",
    website: "https://docs.octra.org",
    twitter: "https://x.com/octra",
    source: "https://docs.octra.org",
  },
  {
    name: "0xio",
    category: "wallets",
    status: "active",
    confidence: "verified",
    description: "non-custodial wallet ecosystem for octra with extension, desktop, mobile, bridge, sdk, and analytics.",
    website: "https://0xio.xyz",
    twitter: "https://x.com/0xio_xyz",
    docs: "https://docs.0xio.xyz",
    source: "https://0xio.xyz",
    featured: true,
  },
  {
    name: "0xio sdk",
    category: "developer",
    status: "active",
    confidence: "verified",
    description: "typescript sdk and developer tooling for building octra dapps with 0xio.",
    website: "https://docs.0xio.xyz",
    twitter: "https://x.com/0xio_xyz",
    source: "https://docs.0xio.xyz",
  },
  {
    name: "0xio dex",
    category: "defi",
    status: "beta",
    confidence: "likely",
    description: "privacy-preserving dex and swap layer from the 0xio ecosystem.",
    website: "https://0xio.xyz",
    twitter: "https://x.com/0xio_xyz",
    source: "https://0xio.xyz",
  },
  {
    name: "atlas",
    category: "explorers",
    status: "beta",
    confidence: "likely",
    description: "network visualization and analytics surface connected to the 0xio ecosystem.",
    website: "https://0xio.xyz",
    twitter: "https://x.com/0xio_xyz",
    source: "https://0xio.xyz",
  },
  {
    name: "octra wallet",
    category: "wallets",
    status: "active",
    confidence: "verified",
    description: "android wallet for octra with account management and open-source tooling.",
    website: "https://octrawallet.com",
    twitter: "https://x.com/octra",
    docs: "https://octrawallet.com/docs/getting-started",
    source: "https://octrawallet.com",
  },
  {
    name: "wallet-gen",
    category: "wallets",
    status: "active",
    confidence: "verified",
    description: "official wallet generation tool from octra labs.",
    website: "https://github.com/octra-labs/wallet-gen",
    twitter: "https://x.com/octra",
    github: "https://github.com/octra-labs/wallet-gen",
    source: "https://github.com/octra-labs/wallet-gen",
  },
  {
    name: "webcli",
    category: "wallets",
    status: "active",
    confidence: "verified",
    description: "official lightweight web client for octra users.",
    website: "https://github.com/octra-labs/webcli",
    twitter: "https://x.com/octra",
    github: "https://github.com/octra-labs/webcli",
    source: "https://github.com/octra-labs/webcli",
  },
  {
    name: "biont network",
    category: "ai agents",
    status: "testnet",
    confidence: "verified",
    description: "autonomous on-chain agents and economy built on octra network.",
    website: "https://www.biont.network",
    twitter: "https://x.com/biontnetwork",
    docs: "https://www.biont.network/docs/getting-started",
    source: "https://www.biont.network",
    featured: true,
  },
  {
    name: "octravpn",
    category: "privacy tools",
    status: "active",
    confidence: "verified",
    description: "decentralized vpn and tailscale-style mesh on octra with on-chain coordination, validator relays, and shielded settlement.",
    website: "https://github.com/androolloyd/octravpn",
    github: "https://github.com/androolloyd/octravpn",
    source: "https://github.com/androolloyd/octravpn",
  },
  {
    name: "pipoke",
    category: "social",
    status: "announced",
    confidence: "likely",
    description: "on-chain social app coming to octra and connected to the biont ecosystem.",
    website: "https://www.biont.network/docs/faq",
    twitter: "https://x.com/pipokeapp",
    source: "https://www.biont.network/docs/faq",
  },
  {
    name: "labz",
    category: "launchpads",
    status: "beta",
    confidence: "verified",
    description: "token launch, trading, portfolio, bridge, and creator rewards platform.",
    website: "https://beta.labz.lol",
    twitter: "https://x.com/labzdotlol",
    source: "https://beta.labz.lol/learning-center",
    featured: true,
  },
  {
    name: "factory amm",
    category: "defi",
    status: "announced",
    confidence: "likely",
    description: "amm and concentrated liquidity dex project announced for the octra ecosystem.",
    website: "https://factory-amm.xyz",
    twitter: "https://x.com/factory_oct",
    source: "https://factory-amm.xyz",
  },
  {
    name: "octane",
    category: "defi",
    status: "in development",
    confidence: "likely",
    description: "open-source defi project in the Octane repository. needs deeper verification before marking verified.",
    website: "https://github.com/octane-defi/Octane",
    github: "https://github.com/octane-defi/Octane",
    source: "https://github.com/octane-defi/Octane",
  },
  {
    name: "applied",
    category: "developer",
    status: "active",
    confidence: "verified",
    description: "octra vm metalanguage and developer layer for building applied programs.",
    website: "https://docs.octra.org",
    twitter: "https://x.com/AppliedLang",
    source: "https://docs.octra.org",
  },
  {
    name: "program examples",
    category: "developer",
    status: "active",
    confidence: "verified",
    description: "official example programs and templates for builders.",
    website: "https://github.com/octra-labs/program-examples",
    twitter: "https://x.com/octra",
    github: "https://github.com/octra-labs/program-examples",
    source: "https://github.com/octra-labs/program-examples",
  },
  {
    name: "ocs01-test",
    category: "developer",
    status: "active",
    confidence: "verified",
    description: "contract pre-testing project for the ocs01 standard.",
    website: "https://github.com/octra-labs/ocs01-test",
    twitter: "https://x.com/octra",
    github: "https://github.com/octra-labs/ocs01-test",
    source: "https://github.com/octra-labs/ocs01-test",
  },
  {
    name: "light-node",
    category: "infrastructure",
    status: "in development",
    confidence: "verified",
    description: "lightweight node and compiler tooling from octra labs.",
    website: "https://github.com/octra-labs/light-node",
    twitter: "https://x.com/octra",
    github: "https://github.com/octra-labs/light-node",
    source: "https://github.com/octra-labs/light-node",
  },
  {
    name: "node configuration",
    category: "infrastructure",
    status: "active",
    confidence: "verified",
    description: "official node setup and configuration resources.",
    website: "https://github.com/octra-labs/node_configuration",
    twitter: "https://x.com/octra",
    github: "https://github.com/octra-labs/node_configuration",
    source: "https://github.com/octra-labs/node_configuration",
  },
  {
    name: "octra online",
    category: "explorers",
    status: "active",
    confidence: "likely",
    description: "community analytics surface for mainnet stats, accounts, bridge, and trading data.",
    website: "https://octra.online",
    twitter: "https://x.com/octra",
    source: "https://octra.online",
  },
  {
    name: "woct liquidity",
    category: "defi",
    status: "active",
    confidence: "verified",
    description: "external market and liquidity tracking for woct trading pairs.",
    website: "https://dexscreener.com/ethereum/0x37730dcf582e4ef54e3398108ff62f824a3500af2de749d71c237b1f7ebd6cd0",
    twitter: "https://x.com/octra",
    source: "https://dexscreener.com/ethereum/0x37730dcf582e4ef54e3398108ff62f824a3500af2de749d71c237b1f7ebd6cd0",
  },
  {
    name: "xpectrum",
    category: "watchlist",
    status: "watchlist",
    confidence: "unverified",
    description: "possible nft/community project connected to octra. needs manual confirmation.",
    website: "https://x.com/xpectrum_xyz",
    twitter: "https://x.com/xpectrum_xyz",
    source: "https://x.com/xpectrum_xyz",
  },
  {
    name: "octane defi",
    category: "watchlist",
    status: "watchlist",
    confidence: "unverified",
    description: "possible defi project. public confirmation is still thin.",
    website: "https://x.com/octane_defi",
    twitter: "https://x.com/octane_defi",
    source: "https://x.com/octane_defi",
  },
  {
    name: "fhex vault",
    category: "watchlist",
    status: "watchlist",
    confidence: "unverified",
    description: "possible wallet or vault project. needs manual confirmation before verified listing.",
    website: "https://x.com/FHEx_Vault",
    twitter: "https://x.com/FHEx_Vault",
    source: "https://x.com/FHEx_Vault",
  },
  {
    name: "op2p",
    category: "watchlist",
    status: "announced",
    confidence: "unverified",
    description: "peer-to-peer marketplace listed in an early ecosystem directory, but not independently verified yet.",
    website: "https://www.octra.app/",
    source: "https://www.octra.app/",
  },
];
